workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - lint
  - build
  - test
  - secret-detection
  - containerize

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: "true"
  IMAGE_TAG_PREFIX: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}

secret_detection:
  stage: secret-detection

format-check:
  stage: lint
  image: $RUST_IMAGE
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

clippy-check:
  stage: lint
  image: $RUST_IMAGE
  variables:
    SQLX_OFFLINE: "true"
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features -- -D warnings

build:
  stage: build
  image: $RUST_IMAGE
  variables:
    SQLX_OFFLINE: "true"
  script:
    - cargo build --workspace --release

test:
  stage: test
  image: $RUST_IMAGE
  variables:
    SQLX_OFFLINE: "true"
  script:
    - cargo test --workspace

containerize-api:
  stage: containerize
  image: docker:28
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker compose build api
    - docker push $IMAGE_TAG_PREFIX-api
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - api/**/*

containerize-job-ingestor:
  stage: containerize
  image: docker:28
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker compose build job-ingestor
    - docker push $IMAGE_TAG_PREFIX-job-ingestor
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      changes:
        - job-ingestor/**/*

containerize-notifier:
  stage: containerize
  image: docker:28
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker compose build notifier
    - docker push $IMAGE_TAG_PREFIX-notifier
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - notifier/**/*
