name: careerbot

services:
  ingestor:
    build:
      context: .
      dockerfile: ingestor/Dockerfile
      args:
        - RUST_IMAGE=${RUST_IMAGE}
    environment:
      - RUST_LOG=${RUST_LOG}
      - DATABASE_URL=${DATABASE_URL}
      - STREAM_URL=${STREAM_URL}
      - STREAM_KEY_JOBS=${STREAM_KEY_JOBS}
    image: ${IMAGE_TAG_PREFIX}-ingestor

  notifier:
    build:
      context: .
      dockerfile: notifier/Dockerfile
      args:
        - RUST_IMAGE=${RUST_IMAGE}
    environment:
      - RUST_LOG=${RUST_LOG}
    image: ${IMAGE_TAG_PREFIX}-notifier

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - RUST_IMAGE=${RUST_IMAGE}
    environment:
      - RUST_LOG=${RUST_LOG}
      - DATABASE_URL=${DATABASE_URL}
    image: ${IMAGE_TAG_PREFIX}-api

  postgres:
    image: postgres:17
    container_name: careerbot-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  pgdata:
  redis-data:
