name: careerbot

services:
  ingestor:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: ingestor/Dockerfile
      args:
        - RUST_IMAGE=${RUST_IMAGE}
    environment:
      - RUST_LOG=${RUST_LOG}
      - DATABASE_URL=${DATABASE_URL}
      - MQUEUE_URL=${MQUEUE_URL}
      - STREAM_KEY_JOBS=${STREAM_KEY_JOBS}
    image: ${IMAGE_TAG_PREFIX}-ingestor

  notifier:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: notifier/Dockerfile
      args:
        - RUST_IMAGE=${RUST_IMAGE}
    environment:
      - RUST_LOG=${RUST_LOG}
      - MQUEUE_URL=${MQUEUE_URL}
      - STREAM_KEY_JOBS=${STREAM_KEY_JOBS}
    image: ${IMAGE_TAG_PREFIX}-notifier

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - RUST_IMAGE=${RUST_IMAGE}
    environment:
      - RUST_LOG=${RUST_LOG}
      - DATABASE_URL=${DATABASE_URL}
    image: ${IMAGE_TAG_PREFIX}-api

  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "your_user"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  redis-data:
