[package]
name = "notifier"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
dotenvy = "0.15.7"
futures = "0.3.31"
redis = { version = "0.32.1", features = ["tokio-comp"] }
reqwest = { version = "0.12.22", default-features = false, features = ["json", "rustls-tls"] }
serde_json = "1.0.141"
shared = { path = "../shared" }
tokio = { version = "1.45.1", features = ["full"] }
tracing = "0.1.41"
